services:
  - type: worker
    name: geniuskexbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
